use quesera;

CREATE VIEW VW_SEMI AS
SELECT DNI_CLI, NOMBRE_CLI,APELLIDO_CLI,DIRECCION_CLI,TELEFONO_CLI,CORREO_CLI,COD_POST_CLI,ID_PRODCLI,ID_PRODUCTOS
FROM CLIENTE AS A JOIN PRODUCTO_CLIENTES AS B
WHERE A.ID_CLIENTE = B.ID_CLIENTE AND ID_PRODUCTOS = 2;



CREATE VIEW VW_PROD_ALMACEN AS
SELECT * FROM PRODUCTO_TERMINADO
WHERE ID_ALMACEN = 11;


CREATE VIEW VW_PROV_ZONA AS
SELECT * FROM PROVEEDOR
WHERE COD_POST_PROV = 1900
ORDER BY NOMBRE_PROV;


CREATE VIEW VW_STOCK AS
SELECT * FROM PRODUCTO_TERMINADO
WHERE STOCK_ACTUAL >= STOCK_MINIMO;


CREATE VIEW VW_PROV_MATERI AS
SELECT DISTINCT CUIT_PROV,NOMBRE_PROV,DIRECCION_PROV, TELEFONO_PROV,CORREO_PROV ,CONTACTO_PROV,
MATERIA,DESCRIP_MATERIA,ID_ALMACEN,ID_TIPO_MATERIA,CANT_MATERIA,LOTE_MATERIA
FROM PROVEEDOR AS A JOIN MATERIA_PRIMA AS B
WHERE A.ID_PROVEEDOR = B.ID_PROVEEDOR ;
 
 
