use quesera;  -- HABILITAR EL USO DEL ESQUEMA QUESERA

DROP TABLE IF EXISTS LOG_AUDITORIA_PC; -- ELIMINACION DE TABLA DE AUDITORIA DE PRODUCTOS-CLIENTES

CREATE TABLE IF NOT EXISTS LOG_AUDITORIA_PC -- CREACION DE TABLA DE AUDITORIA DE PRODUCTOS-CLIENTES
(ID_LOG_PC INT AUTO_INCREMENT,
NOMB_TABLA VARCHAR(100),
ACCION VARCHAR(50) ,
USUARIO VARCHAR(50) , 
FECHA_MODIF DATE ,
HORA_MODIF TIME,
PRIMARY KEY (ID_LOG_PC));

DROP TRIGGER IF EXISTS TRG_CAMBIO_PC ;

DELIMITER // 
CREATE TRIGGER TRG_CAMBIO_PC AFTER INSERT -- CREACION DEL TRIGGER
ON  PRODUCTO_CLIENTES -- TABLA A AUDITAR
FOR EACH ROW
BEGIN 
INSERT INTO LOG_AUDITORIA_PC (NOMB_TABLA,ACCION,USUARIO,FECHA_MODIF,HORA_MODIF) 
VALUES ('PRODUCTO_CLIENTES','INSERT' ,CURRENT_USER() ,NOW(),NOW());
END //
DELIMITER;

INSERT INTO QUESERA.PRODUCTO_CLIENTES (ID_PRODCLI,ID_CLIENTE,ID_PRODUCTOS,CANTIDAD_PROD) VALUES (38,10,1,1); -- INSERCION DE DATOS DE PRUEBA

SELECT * FROM  LOG_AUDITORIA_PC;  -- PRUEBA DESPUES DE INSERTAR DATOS

-- '1', 'PRODUCTO_CLIENTES', 'INSERT', 'root@localhost', '2022-08-04', '13:08:33'    (SE INSERTARON LOS VALORES CORRECTAMENTE)
-- '2', 'PRODUCTO_CLIENTES', 'INSERT', 'root@localhost', '2022-08-04', '13:09:35'
-- '3', 'PRODUCTO_CLIENTES', 'INSERT', 'root@localhost', '2022-08-04', '13:13:04'


-- TRIGGER BEFORE SOBRE CLIENTE

DROP TABLE IF EXISTS LOG_CLIENTE;   -- ELIMINACION DE TABLA QUE ACTUALIZA LAS MODIFICACIONES DE DATOS DE LOS CLIENTE

CREATE TABLE IF NOT EXISTS LOG_CLIENTE -- CREACION DE SEGUNDA TABLA DE ACTUALIZACION DE DATOS DE LOS CLIENTE
(
ID_LOGCLI INT AUTO_INCREMENT ,
DNI_CLI INT ,
ACCION_LC VARCHAR(10) ,
TABLA_LC VARCHAR(50) ,
USUARIO_LC VARCHAR(100) ,
FECHA_LC DATE ,
HORA_LC time ,
PRIMARY KEY (ID_LOGCLI)
);


DROP TRIGGER IF EXISTS TRG_CAMBIOCLI;

  -- SE CREA EL TRIGGER 
DELIMITER //                                          
CREATE TRIGGER TRG_CAMBIOCLI BEFORE UPDATE ON CLIENTE
FOR EACH ROW 
BEGIN
INSERT INTO LOG_CLIENTE (DNI_CLI,ACCION_LC,TABLA_LC,USUARIO_LC,FECHA_LC,HORA_LC)
VALUES (NEW.DNI_CLI,'UPDATE','CLIENTE',CURRENT_USER(),NOW(),NOW());
END // 
DELIMITER;


UPDATE CLIENTE SET DNI_CLI = '14670561' WHERE (ID_CLIENTE = 15); -- ACTULIXZACION DE DATOS

SELECT * FROM LOG_CLIENTE; -- PRUEBA DE DATOS EN TABLA LOG_CLIENTE

-- '1', '14670561', 'UPDATE', 'CLIENTE', 'root@localhost', '2022-08-04', '13:57:03' ( EL RESULTADO FUE SATISFACTORIO)



-- 2DO TRIGGER BEFORE 

DROP TABLE IF EXISTS LOG_MODALMACEN; -- ELIMINACION DE LA TABLA QUE REGISTRA LOS LOG DE LAS MODIFICACINES EN LA TABLA ALMACEN

CREATE TABLE IF NOT EXISTS LOG_MODALMACEN -- CREACION DE LA TABLA LOG QUE REGISTRA LAS MODIFICACIONES EN LA TABLA ALMACEN
(ID_LOGALM INT AUTO_INCREMENT,
ID_ALMACEN  INT,
TABLA_ALM VARCHAR(50),
ACCION_ALM VARCHAR(50) ,
USUARIO_ALM VARCHAR(50) , 
FECHA_ALM DATE,
HORA_ALM TIME ,
PRIMARY KEY (ID_LOGALM));


DROP TRIGGER IF EXISTS TRG_BORRAALM; -- ELIMINACION DEL TRIGGER TRG_BORRAALM
 
 
 -- CREACION DE TRIGGER
DELIMITER // 
CREATE TRIGGER TRG_BORRAALM BEFORE DELETE ON ALMACEN
FOR EACH ROW 
BEGIN
INSERT INTO LOG_MODALMACEN(ID_REGALM,TABLA_ALM ,ACCION_ALM ,USUARIO_ALM,FECHA_ALM,HORA_ALM)
VALUES (OLD.ID_ALMACEN ,'ALMACEN','DELETE',CURRENT_USER(),NOW(),NOW());
END //
DELIMITER;

DELETE FROM ALMACEN WHERE ID_ALMACEN = 15 ; -- SE ELIMINA UN REGISTRO PARA LA PRUEBA DE ELIMINAR UN REGISTRO DE LA TABLA ALMACEN

SELECT * FROM LOG_MODALMACEN;     -- PRUEBA DE DATOS EN TABLA LOG_MODALMACEN

-- '1', '15', 'ALMACEN', 'DELETE', 'root@localhost', '2022-08-04', '14:44:14' ( EL RESULTADO FUE SATISFACTORIO)

